"""
Pydantic schemas for NeuroLearn Analytics layer.

These models represent the data contracts used by:
- Assessment Agent  (writing quiz results)
- Recommendation Agent  (reading mastery / risk)
- Analytics MCP  (shared access layer for all agents)

Do NOT add lesson content, embeddings, or full profile data here.
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


# ----------------------------------------------------------------
# Quiz Attempt
# ----------------------------------------------------------------

class QuizAttemptCreate(BaseModel):
    """Data required to record a single quiz submission."""

    tenant_id: str
    user_id: str
    course_id: Optional[str] = None
    lesson_id: Optional[str] = None
    topic_id: Optional[str] = None
    score_raw: float = Field(default=0, ge=0)
    score_pct: float = Field(default=0, ge=0, le=100)
    total_questions: int = Field(default=0, ge=0)
    duration_sec: Optional[int] = None
    support_mode: Optional[str] = None
    preferred_format: Optional[str] = None


# ----------------------------------------------------------------
# Quiz Answer
# ----------------------------------------------------------------

class QuizAnswerCreate(BaseModel):
    """Data required to record a single question answer within a quiz attempt."""

    tenant_id: str
    user_id: str
    question_id: str
    topic_id: Optional[str] = None
    is_correct: bool
    difficulty: Optional[str] = None
    error_type: Optional[str] = None
    response_time_ms: Optional[int] = None


# ----------------------------------------------------------------
# Learner Topic State
# ----------------------------------------------------------------

class LearnerTopicState(BaseModel):
    """
    Rolling mastery and risk state for a single learner–topic pair.

    Written by the Analytics Service; read by the Recommendation Agent.
    """

    id: Optional[str] = None
    tenant_id: str
    user_id: str
    course_id: Optional[str] = None
    topic_id: str
    mastery_score: float = Field(default=0, ge=0, le=1)
    attempt_count: int = Field(default=0, ge=0)
    avg_score_pct: float = Field(default=0, ge=0, le=100)
    last_score_pct: float = Field(default=0, ge=0, le=100)
    weakness_level: str = "low"   # low | medium | high
    risk_level: str = "low"       # low | medium | high
    last_seen_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


# ----------------------------------------------------------------
# Recommendation
# ----------------------------------------------------------------

class RecommendationCreate(BaseModel):
    """Data required to log a single recommendation generated by an agent."""

    tenant_id: str
    user_id: str
    course_id: Optional[str] = None
    topic_id: Optional[str] = None
    recommendation_type: str          # e.g. "remediation", "advancement", "review"
    recommended_mode: Optional[str] = None   # e.g. "visual", "audio", "text"
    reason: Optional[str] = None


# ----------------------------------------------------------------
# Learner Dashboard (read model)
# ----------------------------------------------------------------

class LearnerDashboard(BaseModel):
    """
    Aggregated analytics view for a single learner.

    Consumed by the Recommendation Agent and the UI layer.
    """

    tenant_id: str
    user_id: str
    weak_topics: list[str] = Field(
        default_factory=list,
        description="topic_ids where weakness_level is 'medium' or 'high'",
    )
    at_risk_topics: list[str] = Field(
        default_factory=list,
        description="topic_ids where risk_level is 'medium' or 'high'",
    )
    topic_states: list[LearnerTopicState] = Field(default_factory=list)
    recent_average_score: Optional[float] = Field(
        default=None,
        description="Mean score_pct across up to 10 most recent quiz attempts",
    )
